[package]
name = "ziptree_nif"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "ziptree_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.30.0"
ziptree = { git = "https://github.com/howsiyu/ziptree-rs.git", rev = "60078c1"}
